-- =====================================================================
-- V1 baseline — 현행 스키마(= JPA 엔티티) 기준.
-- 이 스크립트는 Hibernate 가 엔티티로부터 생성한 CREATE DDL 을 그대로 옮긴 것으로,
-- fresh DB 는 이 스크립트로 생성되고 Hibernate `ddl-auto: validate` 를 통과한다.
-- 기존(운영/개발) DB 는 flyway baseline-on-migrate 로 V1 이 skip 되고 V2 부터 적용된다.
-- SSOT 는 JPA 엔티티 코드다(docs/specs/erd-sync-policy.md).
-- =====================================================================

create table p_order (
    delivery_fee integer not null,
    discount_amount integer not null,
    menu_total_price integer not null,
    total_price integer not null,
    canceled_at timestamp(6),
    created_at timestamp(6) not null,
    created_by bigint,
    deleted_at timestamp(6),
    deleted_by bigint,
    updated_at timestamp(6),
    updated_by bigint,
    user_id bigint not null,
    id uuid not null,
    store_id uuid not null,
    order_number varchar(30) not null unique,
    order_status varchar(30) not null check (order_status in ('PENDING','ACCEPTED','COOKING','DELIVERING','CANCELED','COMPLETED')),
    delivery_address varchar(255) not null,
    delivery_detail_address varchar(255),
    request_message varchar(255),
    primary key (id)
);

create table p_order_item (
    menu_price integer not null,
    quantity integer not null,
    total_price integer not null,
    created_at timestamp(6) not null,
    created_by bigint,
    deleted_at timestamp(6),
    deleted_by bigint,
    updated_at timestamp(6),
    updated_by bigint,
    id uuid not null,
    menu_id uuid not null,
    order_id uuid not null,
    menu_name varchar(100) not null,
    primary key (id)
);

create table p_payment (
    amount bigint not null,
    canceled_at timestamp(6),
    created_at timestamp(6) not null,
    created_by bigint,
    deleted_at timestamp(6),
    deleted_by bigint,
    paid_at timestamp(6),
    refunded_at timestamp(6),
    updated_at timestamp(6),
    updated_by bigint,
    id uuid not null,
    order_id uuid not null unique,
    idempotency_key varchar(100) unique,
    transaction_id varchar(100) not null unique,
    canceled_reason varchar(255),
    failed_reason varchar(255),
    method varchar(255) not null check (method in ('CARD')),
    refunded_reason varchar(255),
    status varchar(255) not null check (status in ('PAID','FAILED','CANCELED','REFUNDED')),
    primary key (id)
);

create table p_region (
    is_active boolean not null,
    is_service_available boolean not null,
    sort_order integer not null,
    created_at timestamp(6) not null,
    created_by bigint,
    deleted_at timestamp(6),
    deleted_by bigint,
    updated_at timestamp(6),
    updated_by bigint,
    id uuid not null,
    name varchar(50) not null,
    primary key (id)
);

create table p_review (
    rating integer not null,
    created_at timestamp(6) not null,
    created_by bigint,
    deleted_at timestamp(6),
    deleted_by bigint,
    updated_at timestamp(6),
    updated_by bigint,
    user_id bigint not null,
    id uuid not null,
    order_id uuid not null unique,
    store_id uuid not null,
    content varchar(255),
    image_url varchar(255),
    primary key (id)
);

create table p_review_reply (
    created_at timestamp(6) not null,
    created_by bigint,
    deleted_at timestamp(6),
    deleted_by bigint,
    updated_at timestamp(6),
    updated_by bigint,
    id uuid not null,
    review_id uuid not null unique,
    store_id uuid not null,
    content varchar(500) not null,
    primary key (id)
);

create table p_user (
    created_at timestamp(6) not null,
    created_by bigint,
    deleted_at timestamp(6),
    deleted_by bigint,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    updated_by bigint,
    role varchar(20) not null check (role in ('CUSTOMER','OWNER','MANAGER','MASTER')),
    address varchar(100) not null,
    nickname varchar(100) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    refresh_token TEXT,
    primary key (id)
);

alter table if exists p_order_item
    add constraint fk_order_item_order
    foreign key (order_id) references p_order;

alter table if exists p_payment
    add constraint fk_payment_order
    foreign key (order_id) references p_order;
